// Generated by CoffeeScript 1.9.1
(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  module.exports = function(dir, encoding) {
    var entries, entry, entryPath, i, len, result;
    result = {};
    if (typeof encoding !== "string") {
      encoding = null;
    }
    entries = fs.readdirSync(dir);
    for (i = 0, len = entries.length; i < len; i++) {
      entry = entries[i];
      entryPath = path.join(dir, entry);
      if (!fs.statSync(entryPath).isDirectory()) {
        result[entry] = fs.readFileSync(entryPath, encoding);
      }
    }
    return result;
  };

}).call(this);
